"""add_unique_tel_to_business

Revision ID: 127a395177f3
Revises: bc29d9e967fa
Create Date: 2026-03-09 11:23:28.782353

"""
from alembic import op
import sqlalchemy as sa


revision = '127a395177f3'
down_revision = 'bc29d9e967fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_businesses_tel', 'businesses', ['tel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_businesses_tel', 'businesses', type_='unique')
    # ### end Alembic commands ###
