"""Update business unique constraint to tel only

Revision ID: 18f2844423b5
Revises: 8fb85729577c
Create Date: 2026-03-03 11:04:41.374996

"""
from alembic import op
import sqlalchemy as sa


revision = '18f2844423b5'
down_revision = '8fb85729577c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_identity', 'businesses', type_='unique')
    op.create_unique_constraint('uq_business_identity', 'businesses', ['tel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_identity', 'businesses', type_='unique')
    op.create_unique_constraint('uq_business_identity', 'businesses', ['nomination', 'ville', 'tel'])
    # ### end Alembic commands ###
