"""Add business table

Revision ID: 28768165e2bf
Revises: b1c2d3e4f5a6
Create Date: 2026-03-03 10:09:14.639883

"""
from alembic import op
import sqlalchemy as sa


revision = '28768165e2bf'
down_revision = 'b1c2d3e4f5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('nomination', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('cp', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('prefixe', sa.String(length=10), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('act', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_businesses_act'), 'businesses', ['act'], unique=False)
    op.create_index(op.f('ix_businesses_cp'), 'businesses', ['cp'], unique=False)
    op.create_index(op.f('ix_businesses_nom'), 'businesses', ['nom'], unique=False)
    op.create_index(op.f('ix_businesses_nomination'), 'businesses', ['nomination'], unique=False)
    op.create_index(op.f('ix_businesses_prefixe'), 'businesses', ['prefixe'], unique=False)
    op.create_index(op.f('ix_businesses_tel'), 'businesses', ['tel'], unique=False)
    op.create_index(op.f('ix_businesses_ville'), 'businesses', ['ville'], unique=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.execute("DROP INDEX IF EXISTS idx_users_role")
    # ### end Alembcic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.alter_column('users', 'email_hash',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index(op.f('ix_businesses_ville'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_tel'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_prefixe'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_nomination'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_nom'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_cp'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_act'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
