"""Add password_hash to users table

Revision ID: 8310fa23de97
Revises: ea1a0b033357
Create Date: 2026-02-05 19:26:29.183323

"""
from alembic import op
import sqlalchemy as sa


revision = '8310fa23de97'
down_revision = 'ea1a0b033357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
