"""Add unique constraint to business table

Revision ID: 8fb85729577c
Revises: 28768165e2bf
Create Date: 2026-03-03 11:03:07.799642

"""
from alembic import op
import sqlalchemy as sa


revision = '8fb85729577c'
down_revision = '28768165e2bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_business_identity', 'businesses', ['nomination', 'ville', 'tel'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_business_identity', 'businesses', type_='unique')
    # ### end Alembic commands ###
