"""add_name_to_users

Revision ID: cb15c86ef7b0
Revises: dd01025878b5
Create Date: 2026-04-21 13:07:34.157584

"""
from alembic import op
import sqlalchemy as sa


revision = 'cb15c86ef7b0'
down_revision = 'dd01025878b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
