"""add columns to user_reports

Revision ID: d16e9379e6f5
Revises: 127a395177f3
Create Date: 2026-03-10 15:29:56.997175

"""
from alembic import op
import sqlalchemy as sa


revision = 'd16e9379e6f5'
down_revision = '127a395177f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_businesses_tel', 'businesses', type_='unique')
    op.add_column('user_reports', sa.Column('reported_value', sa.String(length=255), nullable=True))
    op.add_column('user_reports', sa.Column('fraud_category', sa.String(length=100), nullable=True))
    op.add_column('user_reports', sa.Column('comment', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_reports', 'comment')
    op.drop_column('user_reports', 'fraud_category')
    op.drop_column('user_reports', 'reported_value')
    op.create_unique_constraint('uq_businesses_tel', 'businesses', ['tel'])
    # ### end Alembic commands ###
