"""create business table

Revision ID: d2b4101129bd
Revises: 18f2844423b5
Create Date: 2026-03-05 10:06:38.401141

"""
from alembic import op
import sqlalchemy as sa


revision = 'd2b4101129bd'
down_revision = '18f2844423b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('nomination', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=500), nullable=True),
    sa.Column('code_postale', sa.String(length=10), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('code_pays', sa.String(length=50), nullable=True),
    sa.Column('tel', sa.String(length=20), nullable=True),
    sa.Column('act', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tel', name='uq_business_identity')
    )
    op.create_index(op.f('ix_businesses_act'), 'businesses', ['act'], unique=False)
    op.create_index(op.f('ix_businesses_code_pays'), 'businesses', ['code_pays'], unique=False)
    op.create_index(op.f('ix_businesses_code_postale'), 'businesses', ['code_postale'], unique=False)
    op.create_index(op.f('ix_businesses_nom'), 'businesses', ['nom'], unique=False)
    op.create_index(op.f('ix_businesses_nomination'), 'businesses', ['nomination'], unique=False)
    op.create_index(op.f('ix_businesses_tel'), 'businesses', ['tel'], unique=False)
    op.create_index(op.f('ix_businesses_ville'), 'businesses', ['ville'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_ville'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_tel'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_nomination'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_nom'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_code_postale'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_code_pays'), table_name='businesses')
    op.drop_index(op.f('ix_businesses_act'), table_name='businesses')
    op.drop_table('businesses')
    # ### end Alembic commands ###
