"""add_unique_constraint_to_tel_in_business

Revision ID: dd01025878b5
Revises: 10c0f43bf1d8
Create Date: 2026-03-19 15:42:40.404445

"""
from alembic import op
import sqlalchemy as sa


revision = 'dd01025878b5'
down_revision = '10c0f43bf1d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_businesses_tel', table_name='businesses')
    op.create_index(op.f('ix_businesses_tel'), 'businesses', ['tel'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_tel'), table_name='businesses')
    op.create_index('ix_businesses_tel', 'businesses', ['tel'], unique=False)
    # ### end Alembic commands ###
