"""remove user fk

Revision ID: ea1a0b033357
Revises: 001
Create Date: 2026-02-05 09:36:38.219607

"""
from alembic import op
import sqlalchemy as sa


revision = 'ea1a0b033357'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('user_reports_user_id_fkey', 'user_reports', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('user_reports_user_id_fkey', 'user_reports', 'users', ['user_id'], ['user_id'])
    op.alter_column('user_reports', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
